### ISSUE TITLE
Don't delete locale information from container builds

### ISSUE THREAD

**Issue by 27Bslash6** [greenpeace/planet4-docker#18]
Lack of locale data is causing issues in Wordpress.

**Comment by koyan** [comment]
Ray, I have written in the p4-dev channel (Bellow the part I had tagged you) the real reason for the error. It is caused by the line 
`add_filter( 'locale', array( $this, 'set_locale' ), 11, 1 );`
at https://github.com/greenpeace/planet4-plugin-engagingnetworks/blob/master/classes/controller/menu/class-p4en-settings-controller.php#L17 
Angelos will fix it so that it does not cause a problem. 
Until then you can workaround by assinging a language in the engaging networks settings in wp admin.

**Comment by koyan** [comment]
So, it is NOT the lack of locale on the server.

**Comment by 27Bslash6** [comment]
Thanks for this, I'll confirm next week.

**Comment by 27Bslash6** [comment]
Confirmed, thanks Koyan.  Setting language in the dropdown re-enables media uploads on https://docker.p4.greenpeace.org
